import {sessions} from './data';

const ghBase=typeof window!=='undefined'&&window.location.hostname.endsWith('github.io')?'/veaiskilling':'';
const path=(value:string)=>`${ghBase}${value}`;

export default function ConceptHome({t}:any){
  const participants=sessions.reduce((sum:any,row:any)=>sum+(parseInt(row['Number participants'])||0),0);
  const states=new Set(sessions.map((row:any)=>row.State).filter(Boolean)).size;
  const schools=new Set(sessions.map((row:any)=>row.School).filter(Boolean)).size;
  const objectives=['Summarise the basic ideas and concepts of AI and its applications.','Describe key differences between machine intelligence and human intelligence.','Organise and represent data in forms including text, numbers, images and sounds.','Understand how AI uses data.','Understand ethics and digital responsibility, including digital footprints, privacy and responsible technology behaviour.','Apply conceptual knowledge of AI to everyday activities.','Practise conscious and responsible use of AI.'];
  const agendas=[['Module 1','Understanding AI',['A formal introduction to AI for teachers.','How AI differs from earlier technologies.','AI, machine learning and generative AI, explained with examples.','Examples of AI capabilities and the challenges of using it.','Bias, errors and ethics for conscious and responsible use.']],['Module 2','AI for Teachers',['Translate curricular and extracurricular material into regional languages.','Answer student questions with examples from regional contexts.','Develop intuitive explanations for difficult concepts.','Generate worksheets matched to student needs.','Create adapted activities for children with visual impairments.','Turn textual content into audio for listening comprehension.','Create accessible Word, HTML, PDF and EPUB content.','Generate alternative text for pictures.']],['Module 3','AI for Visual Inclusion',['Explore AI as a substitute for vision.','Understand common considerations when using AI applications.','Use Be My AI, ChatGPT, Seeing AI and OCR applications.']]];
  const faqs=[['What is this curriculum based on?','The material primarily refers to the CBSE AI curriculum, NCERT trainings and Microsoft Elevate for Special Education. It also draws on Perkins School for the Blind and Paths to Literacy for recommendations specific to visual impairment.'],['How long is the training?','Each module typically needs 1.5 hours with a batch of about 20 teachers and includes active participation and interaction.'],['Who can participate?','All teachers and school administrators can participate.'],['Can students participate in the sessions?','Not yet. The current programme is designed for teachers and school administrators.'],['Can teachers teach students what they have learnt?','This is covered during the training session.'],['Are all teachers required to use AI?','No. The programme asks for responsible, informed and conscious use of AI, not mandatory use.']];
  const references=[['CBSE Computational Thinking and Artificial Intelligence','https://cbseacademic.nic.in/ct-ai.html'],['Teaching artificial intelligence to blind and low-vision students','https://www.perkins.org/resource/teaching-artificial-intelligence-to-blv-students/'],['NCERT training resource','https://classroom.google.com/c/Mjc5ODEyMDQzNjcx'],['Seeing AI for indoor navigation','https://www.perkins.org/resource/seeing-ai-indoor-navigation/'],['Lesson ideas for teaching students to use Seeing AI','https://www.pathstoliteracy.org/resource/lesson-ideas-teaching-students-use-seeing-ai-app/'],['Apps that help people with visual impairments recognise objects','https://www.pathstoliteracy.org/resource/7-best-apps-help-people-visual-impairments-recognize-objects/']];
  return <main id="main">
    <section className="hero hero-single"><div><div className="eyebrow">{t[0]}</div><h1>{t[1]}</h1><p>Practical AI skilling that helps educators create accessible learning and helps people with visual impairment access the world with greater independence.</p><div className="actions"><a className="btn primary" href={path('/module-1')}>{t[2]} →</a><a className="btn" href={path('/sessions')}>{t[3]}</a></div></div></section>
    <section className="wrap metrics-section" aria-label="Programme reach"><div className="stats single-quantitative-strip"><div className="stat"><b>{sessions.length}</b><span>sessions</span></div><div className="stat"><b>{states}</b><span>states</span></div><div className="stat"><b>{schools}</b><span>schools</span></div><div className="stat"><b>{participants}</b><span>participants</span></div></div></section>
    <section className="wrap concept-section"><span className="pill">CONCEPT NOTE</span><h2 className="title">Why AI skilling matters</h2><div className="prose"><p>AI is one of the most important emerging technologies to enter everyday life in recent years. Many people already use AI without consciously recognising it. Everyone therefore needs to understand what AI is, along with its benefits, challenges, opportunities and consequences.</p><p>Special educators in schools for the blind can use AI-based solutions to address operational and educational challenges, especially when teaching STEM subjects to children with visual impairments. During Vision Empower Trust's cyber security and safety webinars, teachers described AI as magical, superfast and seemingly all-knowing. People with visual impairments who have access to these tools describe them as a best friend, a source of independence and a way to reduce reliance on sighted help.</p><p>AI also has the potential to substitute for vision for completely blind students. Be My AI, Seeing AI and other applications use image recognition, text-to-speech and speech-to-text to support mobility, orientation and daily living. Vision Empower Trust already promotes assistive technology and digital literacy so the community can leapfrog into STEM careers. AI within existing assistive technologies, and AI as an assistive technology itself, can accelerate this work.</p><p>These developments are encouraging, but users must also understand the boundaries and limitations of AI. This initiative gives beneficiaries a formal introduction to AI, practical use cases, potential issues, best practices and guidance for responsible, informed and conscious use. It also equips participants to take forward lessons from the CBSE Computational Thinking and Artificial Intelligence curriculum.</p></div></section>
    <section className="concept-band"><div className="wrap concept-section"><span className="pill">LEARNING OUTCOMES</span><h2 className="title">Programme objectives</h2><ul className="objective-list">{objectives.map(x=><li key={x}>{x}</li>)}</ul></div></section>
    <section className="wrap concept-section"><span className="pill">THE LEARNING JOURNEY</span><h2 className="title">Three practice-led modules</h2><p className="lead">Each module is planned for 1.5 to 2 hours and includes hands-on participation.</p><div className="agenda-grid">{agendas.map((agenda,i)=><article className="agenda" key={agenda[0] as string}><span className="pill">{agenda[0] as string}</span><h3>{agenda[1] as string}</h3><ul>{(agenda[2] as string[]).map(x=><li key={x}>{x}</li>)}</ul><a href={path(`/module-${i+1}`)}>Open module →</a></article>)}</div><p className="programme-note">Vision Empower Trust invites teachers and school principals to participate in this skilling initiative, conducted under the A4I Project in collaboration with IIIT Bangalore and Microsoft Elevate partners.</p></section>
    <section className="concept-band"><div className="wrap concept-section"><span className="pill">FREQUENTLY ASKED QUESTIONS</span><h2 className="title">Questions about the programme</h2><div className="faq-list">{faqs.map((faq,i)=><details key={faq[0]} open={i===0}><summary>{faq[0]}</summary><p>{faq[1]}</p></details>)}</div></div></section>
    <section className="wrap concept-section references"><span className="pill">REFERENCES</span><h2 className="title">Sources informing the programme</h2><ol>{references.map(reference=><li key={reference[1]}><a href={reference[1]} target="_blank" rel="noreferrer">{reference[0]}</a></li>)}</ol></section>
  </main>;
}
